
services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_LOCAL_OLLAMA=true
      - OLLAMA_OCR_MODEL=llava
      - OLLAMA_TRANSLATION_MODEL=mistral
      # Add other environment variables as needed
      # - OPENAI_API_KEY=your_key_here
      # - DEEPL_API_KEY=your_key_here
    volumes:
      - ./:/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data: